/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Bubble.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.SpeechBubble.geometry} material={materials.SpeechBubble} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/Bubble.glb')
