/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/MainChar.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Base_HumanLPlatform" position={[0.07, 0, 0.01]} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={0.01} />
        <group name="Base_HumanRPlatform" position={[-0.07, 0, 0.01]} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={0.01} />
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.Base_Human} />
          <primitive object={nodes.Base_HumanPelvis} />
          <skinnedMesh name="Boy" geometry={nodes.Boy.geometry} material={materials.Boy} skeleton={nodes.Boy.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/MainChar.glb')
