/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Github({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("./models/TrophiesRoom/github.glb");

  useFrame(() => {
    group.current.position.y += Math.sin(Date.now() * 0.001) * 0.001;
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Curve.geometry}
        material={materials["SVGMat.001"]}
        position={[0, 1.12, 0]}
        rotation={[Math.PI / 2, 0, Math.PI / 4]}
        scale={[100 / 4, 20 / 4, 100 / 4]}
      />
    </group>
  );
}

useGLTF.preload("./models/TrophiesRoom/github.glb");
