/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Diplo({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("./models/TimeLine/Diplodocus.glb");
  return (
    <group ref={group} {...props} dispose={null} scale={[0.002, 0.002, 0.002]}>
      <mesh
        geometry={nodes.Geo_Diplodocus.geometry}
        material={materials.lambert2SG}
      />
    </group>
  );
}

useGLTF.preload("./models/TimeLine/Diplodocus.glb");
