/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("./models/TimeLine/Oncodna.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Curve.geometry}
        material={materials["Material.002"]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={15}
      >
        <mesh
          geometry={nodes.Curve001.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Curve002.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          geometry={nodes.Curve003.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Curve004.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          geometry={nodes.Curve005.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          geometry={nodes.Curve006.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Curve007.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Curve008.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          geometry={nodes.Curve009.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Curve010.geometry}
          material={materials["Material.001"]}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("./models/TimeLine/Oncodna.glb");
