/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Webstanz({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("./models/TimeLine/Webstanz.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Curve.geometry}
        material={materials["SVGMat.001"]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={15}
      />
      <mesh
        geometry={nodes.Curve001.geometry}
        material={materials["SVGMat.002"]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={15}
      />
    </group>
  );
}

useGLTF.preload("./models/TimeLine/Webstanz.glb");
