/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Gameboy({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/models/Gameboy.glb");
  return (
    <group ref={group} {...props} dispose={null} position={[5, 1, 5]}>
      <mesh
        geometry={nodes.Gameboy001.geometry}
        material={materials["Material.001"]}
        rotation={[1.26, 0.21, -0.22]}
      >
        <mesh
          geometry={nodes.Button1.geometry}
          material={materials.buttons}
          position={[0.44, 0.32, 0.29]}
          scale={0.79}
        ></mesh>
        <mesh
          geometry={nodes.Button1001.geometry}
          material={materials.buttons}
          position={[0.26, 0.32, 0.46]}
          scale={0.79}
        ></mesh>
        <mesh
          geometry={nodes.Cube.geometry}
          material={nodes.Cube.material}
          position={[0, 0.3, -0.36]}
          scale={[0.9, 0.3, 0.9]}
        />

        <mesh
          geometry={nodes.Joystick.geometry}
          material={materials["Material.004"]}
          position={[-0.35, 0.32, 0.37]}
        ></mesh>
        <mesh
          geometry={nodes.select.geometry}
          material={materials["Material.002"]}
          position={[-0.12, 0.3, 0.8]}
          rotation={[0, 0.72, 0]}
        ></mesh>
        <mesh
          geometry={nodes.select001.geometry}
          material={materials["Material.002"]}
          position={[0.11, 0.3, 0.8]}
          rotation={[0, 0.72, 0]}
        ></mesh>
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/Gameboy.glb");
