/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef, useState } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useTexture } from "@react-three/drei";

export default function MainChar({ ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/MainChar.glb");

  const texture = useTexture({
    colorMap: `/models/textures/main/Boy_BaseColor.png`,
    roughtnessMap: `/models/textures/main/Boy_Roughtness.png`,
  });
  texture.colorMap.flipY = false;
  const { actions } = useAnimations(animations, group);

  const [animation, setAnimation] = useState("typing");

  useEffect(() => {
    actions[animation].reset().fadeIn(0.32).play();
    return () => actions[animation]?.fadeOut(0.32);
  }, [animation, actions]);

  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      onClick={() =>
        animation === "typing"
          ? setAnimation("Talking")
          : setAnimation("typing")
      }
    >
      <group name="Scene">
        <group
          name="Base_HumanLPlatform"
          position={[0.07, 0, 0.01]}
          rotation={[-Math.PI, 0, -Math.PI / 2]}
          scale={0.01}
        />
        <group
          name="Base_HumanRPlatform"
          position={[-0.07, 0, 0.01]}
          rotation={[-Math.PI, 0, -Math.PI / 2]}
          scale={0.01}
        />
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.Base_Human} />
          <primitive object={nodes.Base_HumanPelvis} />
          <skinnedMesh
            name="Boy"
            geometry={nodes.Boy.geometry}
            skeleton={nodes.Boy.skeleton}
          >
            <meshStandardMaterial
              attach="material"
              map={texture.colorMap}
              roughness={texture.roughtnessMap}
            />
          </skinnedMesh>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/MainChar.glb");
